examples/sdk-playground/packages/server/handle-wrangler-secrets.sh

Without it, running `pnpm dev` fails:
```sh
packages/server dev$ ./handle-wrangler-secrets.sh dev local && wrangler dev src/index.ts --local --env dev
packages/server dev: setting wrangler env vars for env=dev mode=local
packages/server dev: ./handle-wrangler-secrets.sh: 25: Syntax error: redirection unexpected
packages/server dev: Failed
```

Add shebang in example wrangler secret script

---

.eslintrc.json
package.json
pnpm-lock.yaml
src/Discord.ts
src/utils/patchUrlMappings.ts

This PR patches usage of the global `window` variable to ensure the SDK can be used by non-browser environments, like [Remix](https://remix.run/) and [NextJS](https://nextjs.org/)

fix: support ssr and non-browser environments

---

examples/discord-activity-starter/packages/client/src/main.ts

`.innerHTML` is not safe for untrusted & unsanitized content like channel names, use `.textContent` instead.

Fix activity starter xss

---

package.json
src/Discord.ts

As a part of supporting SSR we removed a [very crucial line](https://github.com/discord/embedded-app-sdk/commit/2beca00fa2f07be5a6c6837a95513e24c9de5c8d#diff-63b380e466b8c60959f9ca00e5de37407382df7dd82b8aa4a9d7f896b0e43221L92)
This PR adds it back (with checks for SSR environments)

Add back missing message event listener

---

package.json
src/Discord.ts
src/__tests__/discordSdk.test.ts

This PR adds a minimal test for the DiscordSDK
It runs through constructing the SDK, verifying that the handshake is initiated, and that the sdk resolves being "READY" once a ready event is received.

Add minimal test suite for DiscordSDK constructor

---

.github/workflows/gihub-package-publish.yml
.github/workflows/npm-package-publish.yml
.github/workflows/package-publish.yml

This PR extends the github action that previously published to the github-hosted npm package to also publish directly to npm

chore: extend github action to auto-publish npm

---

.github/workflows/ci.yml

We are getting some funky errors on `pnpm install` specifically from dependabot PRs.  Before trying something else, I want to get on the latest versions of all our actions packages.

chore: bump versions of github actions

---

package.json
pnpm-lock.yaml

Believe it or not, this is blocking an upgrade of jest.  The breaking changes look to be limited to dropping ancient versions of node and browsers:  https://github.com/uuidjs/uuid/blob/main/CHANGELOG.md#900-2022-09-05

fix(deps): update to uuid v9

---

examples/sdk-playground/packages/client/package.json
examples/sdk-playground/packages/client/src/react-app-env.d.ts
examples/sdk-playground/packages/client/src/serviceWorker.ts
pnpm-lock.yaml

Guessing this was a relic from before vite was introduced.  It's way out of date and creating problems with out of date pnpm deps and a npm migration.

chore: remove react-scripts

---

examples/sdk-playground/packages/client/package.json
examples/sdk-playground/packages/client/src/components/ReactJsonView.tsx
pnpm-lock.yaml

`react-json-view` is no longer maintained, and it was causing all kinds of dependency range specifier conflicts:
https://github.com/mac-s-g/react-json-view
I migrated us over to `react-json-tree`, which is part of redux, so I'm hoping it's more likely to be maintained moving forward:
https://github.com/reduxjs/redux-devtools/tree/main/packages/react-json-tree
Tested the changes locally with sdk-playground, and it looks fine.

chore(deps): migrate sdk-playground to react-json-tree

---

.github/workflows/ci.yml

Hopefully this fixes the issue with github install paths in package.json that's breaking dependabot PRs.  There is currently an issue where all PRs submitted by dependabot fail CI, due to `pnpm install` failing:
```
Scope: all 11 workspace projects
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +1080
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1080, reused 0, downloaded 199, added 193
Progress: resolved 1080, reused 0, downloaded 454, added 45[7](https://github.com/discord/embedded-app-sdk/actions/runs/8682264272/job/23806513064?pr=131#step:5:8)
 ERROR  Command failed with exit code 128: /usr/bin/git clone git@github.com:uNetworking/uWebSockets.js.git …
```

build: work around npm install path ssh bug

---

.github/workflows/ci.yml

pnpm v9 was just released, and it does _not_ work with our current lock file. Pinning us in CI until we can sort it out.

build: pin version of pnpm in CI

---

examples/react-colyseus/README.md

This updates the docs to address issues of incomplete packages when pnpm install not run from root of repo
Related issue: https://github.com/discord/embedded-app-sdk/issues/39

chore: call out explicit path for install and running examples

---

examples/discord-activity-starter/packages/client/package.json
examples/discord-activity-starter/packages/client/tsconfig.json
examples/discord-activity-starter/packages/client/vite.config.ts
examples/react-colyseus/packages/client/package.json
examples/react-colyseus/packages/client/tsconfig.json
examples/react-colyseus/packages/client/vite.config.ts
examples/sdk-playground/packages/client/package.json
examples/sdk-playground/packages/client/tsconfig.json
examples/sdk-playground/packages/client/vite.config.ts
pnpm-lock.yaml

Vite 5 seems to throw warnings on commonjs projects, so I went ahead and moved the client projects in the examples over to esm.
It also was defaulting to a random port, so I added port 3000 in the config.  I'm not sure if this will cause problems in production or not, so please keep me honest here.

chore: update samples to vite 5.x

---

examples/discord-activity-starter/packages/client/package.json
examples/discord-activity-starter/packages/client/src/main.ts
examples/react-colyseus/packages/client/package.json
examples/react-colyseus/packages/client/src/hooks/useAuthenticatedContext.tsx
examples/react-colyseus/packages/client/src/types.tsx
examples/sdk-playground/packages/client/package.json
examples/sdk-playground/packages/client/src/types.tsx
pnpm-lock.yaml
src/commands/index.ts
src/index.ts

The SDK exposed similar functionality already. This pattern leans on using generics to retrieve the object shape for command input and responses. The example below is contrived, better use-cases will be more complicated... but, this is an example of basic usage.
```ts
import type {CommandInput, CommandResponse} from '@discord/embedded-app-sdk';
import { discordSdk } from './discordSdk';
async function foo() {
const getChannelInput: CommandInput<'getChannel'> = { channel_id: discordSdk.channelId };
let getChannelReply: CommandResponse<'getChannel'>;
getChannelReply = await discordSdk.commands.getChannel(getChannelInput);
}
```
As a part of this PR we're also removing the package `type-fest` which was previously used for `AsyncReturnType`. Turns out they're doing the same thing under the …

Feat: Add CommandInput and CommandResponse as types

---

renovate.json

I think `/examples` is automatically ignored by default in renovate, so those underlying `package.json` files in examples aren't currently being scanned.  I believe this is part of the standard config:  https://docs.renovatebot.com/presets-default/#ignoremodulesandtests

chore: use explicit renovate ignore paths

---

src/commands/setActivity.ts

Somehow with the upgrading of packages, we're now properly detecting that we're trying to "pick" from "Activity" some options that never existed in "Activity". This PR removes the never-available options `button` and `supported_platforms`

fix: remove unavailable options from "setActivity" command

---

README.md
examples/discord-activity-starter/packages/client/src/main.ts
examples/nested-messages/client/utils/initializeSdk.ts
examples/react-colyseus/packages/client/src/hooks/useAuthenticatedContext.tsx
examples/sdk-playground/packages/client/src/actions/authActions.ts

This is the first step of https://app.asana.com/0/1207125399187322/1207144243089950 . I'm updating the sdk-playground auth example and the other examples in this repo to add the `applications.commands` scope. When a user authorizes this scope for the user (rather than a guild), that will install the app to the user.
Additionally, we will have to do a migration that updates existing 1p / 3p-partner apps to
- be user installable and guild installable and
- have a primary entry point app command that launches an activity.
We can't update the requested auth scopes in the iframe code for the app developers though, so I'm going to point the 1p / 3p-partner developers to this example and ask them to make this one line change.
With this example, I'm making the following assumptions:
- Using the …

update auth examples with applications.commands scope

---

examples/discord-activity-starter/packages/client/src/main.ts
examples/sdk-playground/packages/client/src/App.tsx
examples/sdk-playground/packages/client/src/pages/CurrentGuildMember.tsx
src/schema/common.ts
src/schema/events.ts

Adds support for activities to read guild member profiles' changes via RPC subscription. App side work still in progress

feat: add UPDATE_CURRENT_GUILD_MEMBER sdk hook and playground page

---

examples/sdk-playground/example.env
examples/sdk-playground/packages/client/package.json

they aren't really useful anymore, as they were intended for when there was no CSP exception for `https://discord.com/api`

chore: rm sdk-playground "proxy" envs

---

src/utils/__tests__/matchAndRewriteRoute.test.ts
src/utils/patchUrlMappings.ts

fix: do not prepend PROXY_PREFIX if already prepends path

---

docs/local-sdk-development.md
src/utils/patchUrlMappings.ts
tsconfig.json

Currently, when a new `script` tag is created via an imported JavaScript package, we are changing the `src` attribute for that script tag when it goes through the normal `MutationObserver` flow. However, a refetch doesn't happen; `MutationObserver` only goes off when the HTML element is added, but never stops the outgoing request.
With this change, if the `MutationObserver` sees that it's modifying a `<script src=` attribute, it'll instead create a new `script` tag in the DOM next to the one it would have modified, and then destroy the original. Unfortunately this will still show the error from the request blocked by the CSP, but it will go off separately and make the new request with the second script tag as well, loading in the content.
**I'd be curious to collect thoughts on this …

fix(patchUrlMappings): recreate script elements when patching their src attribute

---

README.md

someone in ddevs pointed out that this README snippet doesn't work out of the box, and needs `/.proxy`

docs: add .proxy to /api/token call in README

---

src/utils/__tests__/matchAndRewriteRoute.test.ts
src/utils/patchUrlMappings.ts
src/utils/url.ts

We already do this in `attemptRemap` but we need to apply it in `matchAndRewriteURL` as well.
It's worth asking, why are we checking this twice? Why are we adding `/.proxy` in two places?
In case the original url has no matching urls to map to, we *still* want to inject the `/.proxy` path.

fix: prevent multiple remappings from applying the .proxy path twice

---

package.json
src/Discord.ts
src/mock.ts

The `GET /applications/<application_id>/activity-instances/<instance_id>` endpoint returns Activity instances with a location ID that does not necessarily refer to a channel. Discord passes the `location_id` query parameter to the iframe, so the Activity can compare that location ID with the location ID in the response from the `GET /applications/<application_id>/activity-instances/<instance_id>` endpoint.
This PR adds a `locationId` property to the SDK for reading that query parameter more easily.

add location ID to SDK

---

src/generated/schema.json
src/generated/schemas.ts

another `npm run sync` based on recent changes.
Note: This is a breaking change! Consumers won't have any problems running the code if they're passing through a `referrer_id` but if they're relying on the types the compiler will yell at them.

feat!: remove referrer_id from shareLink API

---

src/commands/setActivity.ts
src/schema/common.ts

as part of a change that just went out today, we now support new fields for rich presence activities:
- `state_url` - URL that is linked to when clicking on the state text in the activity card
- `details_url` - URL that is linked to when clicking on the details text in the activity card
- `assets.large_url` - URL that is linked to when clicking on the large image in the activity card
- `assets.small_url` - URL that is linked to when clicking on the small image in the activity card
this PR adds support for those fields to the embedded app sdk
there is a docs pr to update documentation here: https://github.com/discord/discord-api-docs/pull/7674

feat: add new URL fields

---

src/generated/schema.json
src/generated/schemas.ts
src/schema/events.ts

- ran `npm run sync` 
- automatically updated a number of generated commands 
- added `GET_QUEST_ENROLLMENT` and `QUEST_START_TIMER` commands 
- manually added `QUEST_ENROLLMENT_STATUS_UPDATE` event

feat: add Quests commands + event 
